### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by jim1506** [waveygroup/sweetalert#8]
I wrote a simple test in my controller:

```
 if (session('checked') == 0) {
            Sweetalert::basic('we are checking some details', 'update');
            return redirect()->route('adminHome');
            //return view('admin.dashboard');
        }
```

and got 

syntax error, unexpected '|', expecting ';' or '{'

with the error pointing to 

vendor/wavey/sweetalert/src/Notifier.php:111

Which is highlighting

`protected function buildJsonConfig(): bool|string

    {

        return json_encode( $this->config );

    }`

**Comment by debugdotdog** [comment]
Hello @jim1506, Thank's for posting the issue, I will push an update today to fix this! 😀

**Comment by debugdotdog** [comment]
@jim1506 Could you please provide me your setup, for example what PHP version are you using? And what version of Laravel are you using? This will help me reproduce your bug and fix it :)

**Comment by debugdotdog** [comment]
@jim1506 After testing, it seems to work using a new Laravel application (Version 9) on PHP 8. I assume that you are running PHP 7 and an older version of Laravel. I have pushed an update to remove the union return types for the `buildJsonConfig()`, please update the package on your end and let me know if this fixes your issue.

**Comment by jim1506** [comment]
I did a composer update but your package was not updated.

**Comment by jim1506** [comment]
I am using Laravel 8I am using Laravel 8

**Comment by debugdotdog** [comment]
@jim1506 Could you try adding "dev-master" into your composer.json file and then try, thanks buddy for letting me know. Alliteratively, I have made a release, so you should now be able to use the composer update correctly. Sorry for the hassle.

**Comment by jim1506** [comment]
I have done this but am still getting an error
![2022-04-08_10-12-18](https://user-images.githubusercontent.com/123184/162404843-fed1cd12-1a42-480e-b1f6-46646bdc166b.png)

**Comment by debugdotdog** [comment]
@jim1506 Could you show your package.json file please? Alongside this, I would suggest removing the package from your vendor folder, should be `rm -rf /vendor/wavey/sweetalert` and then ensuring that your trying to pull the latest version inside your composer file, and then run install again. From what I can see, the error is still showing due to the update not being pulled down. 

Sidenote, you may need to remove the entry from the composer.lock file too, as it may be picking the earlier version to download.

**Comment by debugdotdog** [comment]
Another issue I noticed is with some other returns, I have published another fix for this, however please perform the actions above and let me know if this fixes your issue. 

If you need more help, feel free to reach me on my email `kieran at wavey dot group` and we could jump into a team or google meets call and I can assist you if you like.

**Comment by jim1506** [comment]
OK I have done all this and am now getting the following error:
![2022-04-08_22-09-40](https://user-images.githubusercontent.com/123184/162531984-2c33c0c8-0028-4c0f-997f-b202ae83c657.png)

**Comment by debugdotdog** [comment]
@jim1506 Another release has been made, if you can update again it should now be working. Let me know if you have any more issues.

**Comment by jim1506** [comment]
It is failing still with 

syntax error, unexpected 'static' (T_STATIC)

 function html(): static

**Comment by debugdotdog** [comment]
@jim1506 My apologies, I have been out of the office until this morning, I have published another updated for you, let me know of any other issues.

**Comment by debugdotdog** [comment]
Hello @jim1506, I assume that this issue is now fixed on your end so I will close the issue, if you have any more problems, feel free to reopen the issue.
